### ISSUE TITLE
Advancements don't always save properly when travelling between servers

### ISSUE THREAD

**Issue by GoldenDelicios** [DaMarine/Slabserver-Bugs#30]
There seems to be a few cases of advancements not being saved when travelling between the MW and RW.
Most notable example is "A Resourceful Journey" when travelling from MW to RW, but I was able to reproduce this by completing "Ender Evolution" in the RW end dimension and then using the end portal to get back to the MW.

**Comment by DaMarine** [comment]
Interesting that this is affecting Ender Evolution given the changes we just made to make it work on RW. The only thing I can think of is that this is being triggered by RW<->MW transitions - thoughts, @chrissamael and @DidsheMa?

**Comment by chrissamael** [comment]
Things I could think be causing this:
 - Different namings in the advancements on the two servers
 - Data not being reloaded on player join

For "A Resourceful Journey": which one is that again? MW->RW or RW->MW? Because, for the latter, I added a PMS message sent to slab so that the player gets this advancement silently on join on MW.

The data not being reloaded issue is something I have come across very few times in development and know it can be an issue, but haven't found anything that would give me control over the playerdata loaded in the server. Hence the above mentioned safe-guard for the RW->MW advancement.

**Comment by DaMarine** [comment]
The namings are definitely identical (alongside all advancements atm, which helps rule out any inconsistencies). Resourceful Journey is MW->RW.

**Comment by chrissamael** [comment]
This has only happened once to a single player since introducing the fixes, when 10 players simultaneously left the RW, which is obviously a fringe case. In our current implementation this is a fringe case we'll have to live with, as we have no further means of controlling this aspect of the inner workings of a minecraft server, sadly. Until a potential rewrite we just have to accept this for now.
