### ISSUE TITLE
Players kicked during restart are shown as online by /who command

### ISSUE THREAD

**Issue by XeDotCom** [DaMarine/Slabserver-Bugs#41]
**Describe the bug**
Accounts which were kicked during restart is shown as online by the `/who` command.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get kicked during a restart.
2. Do `/who [ingamename]`
3. See error

**Expected behaviour**
It should show you are offline.

**Screenshots**
[Altman007 (was kicked during a restart)](https://cdn.discordapp.com/attachments/596920517643206656/883322640264212510/unknown.png)

**Additional context**
Was found accidentally.

**Comment by chrissamael** [comment]
Fixed in latest release, have yet to sort out my eclipse to push the release but have uploaded the change documented [here](https://github.com/chrissamael/AfkSleep/commit/d607525f239a34d11d3ebccd170a76b7a3b2e0de) to live.
I'm pretty sure I had fixed this at an earlier point of time, might have reverted at some point.
