### ISSUE TITLE
Global Tab List

### ISSUE THREAD

**Issue by DaMarine** [DaMarine/Slabserver-Bugs#9]

**Comment by DidsheMa** [comment]
Problematic because this has to take into account several things:
1) having to be available for DiscordSRV at any time
2) Slab's custom sleep and /away plugins
3) having to be at Bungee level because the paper servers each only know "their" players, but Bungee doesn't really do tab lists ingame

Chris and I briefly talked about this today and were leaning towards (heh) another database table where everything can just hook into as the best catch-all solution...

https://www.spigotmc.org/resources/bungeetablistplus.313/ this seems worth investigating too, comes with lots of customization options and an API

**Comment by chrissamael** [comment]
I gave the BungeeTablistPlus Plugin a go, had it configured to simulate a vanilla tablist (without hearts and the like, as those are tied to scoreboards which are tied to servers)

This is what I used as tabLists/default.yml:
`showTo: all
priority: 1

showHeaderFooter: false
header:
- "&cWelcome &f${viewer name}"
- "&eW&celcome &f${viewer name}"
- "&eWe&clcome &f${viewer name}"
- "&eWel&ccome &f${viewer name}"
- "&eWelc&come &f${viewer name}"
- "&eWelco&cme &f${viewer name}"
- "&eWelcom&ce &f${viewer name}"
- "&eWelcome &f${viewer name}"
- "&cW&eelcome &f${viewer name}"
- "&cWe&elcome &f${viewer name}"
- "&cWel&ecome &f${viewer name}"
- "&cWelc&eome &f${viewer name}"
- "&cWelco&eme &f${viewer name}"
- "&cWelcom&ee &f${viewer name}"
- "&cWelcome &f${viewer name}"
headerAnimationUpdateInterval: 0.2
footer: "&f&oPowered by BungeeTabListPlus"

type: DYNAMIC_SIZE

customPlaceholders:
  other_server_prefix: # makes players on other servers gray
    !conditional
    condition: ${viewer server} == ${player server}
    true: "&f"
    false: "&7"

# Hidden players show up on the tab list, avoids glitches
hiddenPlayers: VISIBLE

playerSets:
  all_players: all

playerSet: all_players

playerOrder: "server viewer-first, server asc, name asc"

playerComponent: "${player luckpermsbungee_prefix}${player name}"`

which resulted in this kind of tablist: 
![image](https://user-images.githubusercontent.com/12401196/84948479-16d43d80-b0ec-11ea-9599-43dd1a5f38ce.png)

We tested it with a player on each sever, worked just fine 👍

**Comment by Frogperson** [comment]
I also tested this plugin, but it unfortunately conflicts with our #away and #idle statuses in tab, which in turn breaks our `playerlist` integration in #ingamechat. This feature is likely going to have to wait until the sleep/playeractivity plugin rewrite (which is coming soon™).

**Comment by chrissamael** [comment]
Added TAB plugin with correct configuration, seems to be working just fine :) Would keep this ticket open for another week before closing.

**Comment by chrissamael** [comment]
Working fine 👍
